apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - persistent-gcpaugvolume.yaml
  - augfilestorage-claim.yaml
  - ac-backendconfig.yaml
  - backend-deployment.yaml
  
commonLabels:
  author: juan.currea	
  stage: dev
  
configMapGenerator:
  - name: backend-proxy-conf
    files: 
      - config-files/nginx.conf

namespace: coding

images:
- name: gcr.io/augmented-coding-glb001/augmented-coding-be:v2.4.0
  newTag: v2.5.0
  
patchesStrategicMerge:
- resources-patch.yaml
