kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: coding

spec: 
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          resources:
            limits:
              cpu: '5'
              memory: 50G
            requests:
              cpu: '3'
              memory: 25G
